#!/usr/bin/env node
/* Writes src/levels.js from tools/levelspec.js + tools/art.js pictures + tools/tuned/L<id>.json lanes,
   and src/levels_grids.txt (plain picture dump). Usage: node tools/make_levels.js */
const fs = require('fs'), path = require('path');
const { ART } = require('./art');
const { LEVELS } = require('./levelspec');
const root = path.join(__dirname, '..');
let out = `/* Betri Hundar levels – GENERATED by tools/make_levels.js from tools/levelspec.js (+ tools/art.js pictures,
   tools/tuned/*.json doghouse lanes). Edit those and re-run; verify with \`node tools/solver.js --src\`.
   grid: 24x24 rows separated by spaces. Colours: R O Y G C B P K W N D.
   lanes: doghouse queues separated by '|'. Token = colour + count + breed (none=Labrador, d=pylsuhundur, h=husky).
   tier: t/e = auðvelt, m = miðlungs, h = Erfitt, x = Mjög erfitt (sawtooth difficulty). */
const LEVEL_DEFS = [\n`;
let dump = '';
for (const L of LEVELS) {
  const t = JSON.parse(fs.readFileSync(path.join(root, 'tools/tuned/L' + L.id + '.json'), 'utf8'));
  const rows = ART[L.art]().g.map(r => r.join(''));
  out += `  { id: ${L.id}, name: '${L.name}', tier: '${L.tier}', dog: '${L.dog}',${L.hint ? ` hint: '${L.hint}',` : ''}\n` +
    `    grid: \`${rows.join('\n           ')}\`,\n    lanes: '${t.lanes}' },\n`;
  dump += `${L.id} ${L.name} (${L.tier})\n${rows.join(' ')}\n`;
}
out += '];\n';
// daily bank: pre-tuned medium / hard / very hard lanes per picture (keyed by level id)
const bank = {};
for (const L of LEVELS) for (const t of ['m', 'h', 'x']) {
  const f = path.join(root, 'tools/tuned/daily', L.art + '_' + t + '.json');
  if (fs.existsSync(f)) { const j = JSON.parse(fs.readFileSync(f, 'utf8')); if (j.inBand) (bank[L.id] = bank[L.id] || {})[t] = j.lanes; }
}
out += `/* Daily-puzzle bank (GENERATED): tier-tuned doghouse lanes for each picture; see PL.genDaily. */\nconst DAILY_BANK = ${JSON.stringify(bank, null, 0).replace(/\],?"/g, m => m).replace(/},"/g, '},\n  "')};\n`;
console.log('daily bank entries:', Object.values(bank).reduce((a, o) => a + Object.keys(o).length, 0));
fs.writeFileSync(path.join(root, 'src/levels.js'), out);
fs.writeFileSync(path.join(root, 'src/levels_grids.txt'), dump);
console.log('wrote src/levels.js with', LEVELS.length, 'levels');
